[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
feed = "6BKcCM11A3dRkaf21Lnhqrj1XGMSifd7VA3oCfwNe5bX"
guard = "FyJvcrTMrMbzSmqTkwY7h8AkVR4BYq2pQrfgXmN1jh5M"
irm = "8gnZd9Hsx9YZZwNXgAXR8odRstSdKH2cETNfrg661oKE"
jbl = "D33b3Lb42BGyUQZyftS52idrwsjMy8jYqjb6V4ow1RxD"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run test"

[hooks]
