[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
faucet = "HALzjfshwyYKYjLNL6ectL9oBoM3tLcUCAabZNYrxwWy"
feed = "orcdW2S1VR5kt8axERS4cJuiywxLPKo3qYYqN3Di5s4"
guard = "grddH13wp77vjwV2WwzbVXAkgRGQuTHkj1hKcECtHRt"
quote = "QUoTDMDSEw1nAFRp27eWrK4AcVsE1Sg9YupYcc22Yhc"
irm = "irmdacogiedKeCEBh72FJx4aoixyaByqGikTkxGifUk"
calma = "c1md3yLhwBxREDRc2HcX4ivTigoyJ3No3DehkzjaPT8"

[programs.localnet]
faucet = "HALzjfshwyYKYjLNL6ectL9oBoM3tLcUCAabZNYrxwWy"
feed = "orcdW2S1VR5kt8axERS4cJuiywxLPKo3qYYqN3Di5s4"
guard = "grddH13wp77vjwV2WwzbVXAkgRGQuTHkj1hKcECtHRt"
quote = "QUoTDMDSEw1nAFRp27eWrK4AcVsE1Sg9YupYcc22Yhc"
irm = "irmdacogiedKeCEBh72FJx4aoixyaByqGikTkxGifUk"
calma = "c1md3yLhwBxREDRc2HcX4ivTigoyJ3No3DehkzjaPT8"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
link-keys = "mkdir -p target/deploy && ln -sf ~/.config/solana/calma/orcdW2S1VR5kt8axERS4cJuiywxLPKo3qYYqN3Di5s4.json target/deploy/feed-keypair.json && ln -sf ~/.config/solana/calma/grddH13wp77vjwV2WwzbVXAkgRGQuTHkj1hKcECtHRt.json target/deploy/guard-keypair.json && ln -sf ~/.config/solana/calma/irmdacogiedKeCEBh72FJx4aoixyaByqGikTkxGifUk.json target/deploy/irm-keypair.json && ln -sf ~/.config/solana/calma/QUoTDMDSEw1nAFRp27eWrK4AcVsE1Sg9YupYcc22Yhc.json target/deploy/quote-keypair.json && ln -sf ~/.config/solana/calma/c1md3yLhwBxREDRc2HcX4ivTigoyJ3No3DehkzjaPT8.json target/deploy/calma-keypair.json && ln -sf ~/.config/solana/calma/HALzjfshwyYKYjLNL6ectL9oBoM3tLcUCAabZNYrxwWy.json target/deploy/faucet-keypair.json"

[hooks]
