[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
jbl = "6pMJEHx5jRwwt85bKijyfkSgzhQ5bmurDdejBiopAQ7y"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run test"

[hooks]
