[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
math = { path = "../math" }
state = { path = "../state" }
interface = { path = "../interface" }
irm-state = { path = "../irm-state" }
feed-state = { path = "../feed-state" }
anchor-lang = { version = "1.0.2", default-features = false }
wasm-bindgen = "0.2"
bytemuck = "1.14"
solana-sdk-ids = "3.1.0"

[dev-dependencies]
wasmtime = "28"
